### ISSUE TITLE
[v0.11] testing of build 0.11.0.v20161106-1459

### ISSUE THREAD

**Issue by anb0s** [anb0s/eclox#172]
I need help with testing of the build
tag: **...**
commit: **e0d4fdcac8233b23857fdb9ec797b1b60ce4020e**

It is available at the testing update site now: http://anb0s.github.io/eclox/testing
version: **eclox 0.11.0.v20161106-1459**

**Use "Help | Install New Software...", paste the link and select the right version!**

new found issues and enhancement requests:
- [x] #173 [v0.11] invalid custom doxygen identifier found
- [x] #174 [v0.11] endRule without matching beginRule
- [x] #175 java.lang.IllegalArgumentException: endRule without matching beginRule
- [x] #176 Support resources in linked folders

new fixed issues in this build:
- [x] #167 Scrollbar missing for Input Directories in Graphical Editor

fixed issues with previous build(s):
- [x] [v0.11] testing of build 0.11.0.v20161101-1923
  - [x] #11 muliple Doxyfiles - editing
  - [x] #12 Import of existing configuration files
  - [x] #15 Add ability to use Doxyfile not in project scope
  - [x] #68 open a file that is not a resource in eclipse
  - [x] #75 relative or project-based path to doxygen.exe
  - [x] #86 environment variables needed for some doxyfiles
  - [x] #87 working directory not configurable
  - [x] #114 Improvement static declaration of plugin relative identifier
  - [x] #144 Tell more about the directory where eclox is stared
  - [x] #161 migrate to GitHub
  - [x] #163 Unable to use GraphViz
  - [x] #164 Unable to create the selected preference page. eclox/core/ui/PreferencePage : Unsupported major.minor version 52.0
  - [x] #165 new GitHub update site shows only one version "Eclox 0.10.2.201508272130"
  - [x] #170 Graphviz and PlantUML on Windows

**Comment by anb0s** [comment]
new build #177
