### ISSUE TITLE
[v0.11] testing of build 0.11.1.v20170413-1523

### ISSUE THREAD

**Issue by anb0s** [anb0s/eclox#188]
I need help with testing of the build
tag: **..**
commit: **f3020c10a18bae1af674297c993af0106ae787fd**

It is available at the testing update site now: http://anb0s.github.io/eclox/testing
version: **0.11.1.v20170413-1523**

Doxygen Binaries (Bundle): http://anb0s.github.io/eclox
version: **1.8.13.v20170413-1543**

**Use "Help | Install New Software...", paste the link and select the right version!**

new found issues and enhancement requests:
...

new fixed issues in this build:
- [x] #175 java.lang.IllegalArgumentException: endRule without matching beginRule
- [x] #186 NPE when trying to create new Doxyfile
- [x] #187 obsolete settings are not marked
- [x] #189 Doxygen binaries 1.8.13.v20170413-1543

fixed issues with previous build(s):
...

**Comment by anb0s** [comment]
released as eclox-0.11.1
