### ISSUE TITLE
[v0.11] testing of build 0.11.2.v20170504-1955

### ISSUE THREAD

**Issue by anb0s** [anb0s/eclox#194]
I need help with testing of the build
tag: **..**
commit: **941fefd37f2581837974d76a56efef06540bc30c**

It is available at the testing update site now: http://anb0s.github.io/eclox/testing
version: **0.11.2.v20170504-1955**

Doxygen Binaries (Bundle): http://anb0s.github.io/eclox
version: **1.8.13.v20170413-1543**

**Use "Help | Install New Software...", paste the link and select the right version!**

new found issues and enhancement requests:
...

new fixed issues in this build:
- [x] #191 exception after build if OUTPUT_DIRECTORY is an absolute path
- [x] #192 add Eclipse 4.2 target platform
- [x] #193 fix feature and plugin provider-name

fixed issues with previous build(s):
...

**Comment by madsci77** [comment]
With Java 8 it now completes without crashing, so that part seems to be fixed.  Still doesn't show up in CodeWarrior with the default JVM, which appears to be 1.6.0_15.  I may try running CW in Java 8 for a while and see if anything horrible happens.

**Comment by anb0s** [comment]
Yes, as already said i've set eclox plugins to minimum Java 7 in 0.11.x. 

I do not want to go back and support Java 1.6 again, because then i cannot refactor and improve the code in future with Java 7/8 features. BUT if there are some users that want to have eclox for Java 6 i can try to provide builds for 0.11.x steam.

Anyway i will switch again to Java7/8 with 0.12 or 1.x releases...

**Comment by HolgerNie** [comment]
While trying to update I get the follwing error
![eclox](https://cloud.githubusercontent.com/assets/12135505/25791951/eeb0ead6-33c3-11e7-86f6-8899bdd40fe7.PNG)

**Comment by anb0s** [comment]
I've installed this version at two different machines now from update site without problems. Maybe there was a network problem @GitHub... Please try again...

**Comment by HolgerNie** [comment]
After changing the address to **https**://anb0s.github.io/eclox/testing it works

**Comment by anb0s** [comment]
I saw such problems with other update sites too. It has something to do with Eclipse p2 cache. 
Go to Preferences "Available Software Sites", select the update site and use "Reload":
![image](https://cloud.githubusercontent.com/assets/95811/25840206/3a5caa24-349b-11e7-914d-04c4790e9679.png)
I've tried with https and http multiple times and it worked...

**Comment by anb0s** [comment]
released 0.11.2

https://github.com/anb0s/eclox/releases/tag/eclox-0.11.2
