### ISSUE TITLE
[v0.12] testing of build 0.12.0.v20170705-1928

### ISSUE THREAD

**Issue by anb0s** [anb0s/eclox#202]
I need help with testing of the build
tag: **V0_12_0_BETA_1**
commit: **2b91ced4890ca33634949707e798aaaae9dcd7a8**

It is available at the testing update site now: http://anb0s.github.io/eclox/testing
version: **0.12.0.v20170705-1928**

Doxygen Binaries (Bundle): http://anb0s.github.io/eclox
version: **1.8.13.v20170413-1543**

**Use "Help | Install New Software...", paste the link and select the right version!**

new found issues and enhancement requests:
...

new fixed issues in this build:
- [x] #195 java.lang.IllegalArgumentException in createMarkersForResource
- [x] #196 terminate build is not working like expected
- [x] #197 doxygen history menu shows multiple entries for same file
- [x] #198 doxyfile selection dialog does not show nested elements
- [x] #200 invalid custom doxygen identifier found
- [x] #201 Doxygen Build Console: stderr and stdin are not synchronized

fixed issues with previous build(s):
...

**Comment by anb0s** [comment]
new build #205
