### ISSUE TITLE
[v0.12] testing of build 0.12.0.v20170802-2053

### ISSUE THREAD

**Issue by anb0s** [anb0s/eclox#205]
I need help with testing of the build
tag: **V0_12_0_BETA_2**
commit: **877fe607eeafc44560a2026b2012f92c0fb4e4f0**

It is available at the testing update site now: http://anb0s.github.io/eclox/testing
version: **0.12.0.v20170802-2053**

Doxygen Binaries (Bundle): http://anb0s.github.io/eclox
version: **1.8.13.v20170413-1543**

**Use "Help | Install New Software...", paste the link and select the right version!**

new found issues and enhancement requests:
- [ ] #206 [v0.12] console icons are not shown
- [ ] #207 [v0.12] exception if new file created
- [ ] #208 [v0.12] java.lang.NullPointerException in Advanced tab

new fixed issues in this build:
- [x] #199 add "clear history" to history menu
- [x] #203 remove from history if "eclox.core.doxygen.RunException: Missing or bad doxyfile"

fixed issues with previous build(s):
- [x] #202 [v0.12] testing of build 0.12.0.v20170705-1928
  - [x] #195 java.lang.IllegalArgumentException in createMarkersForResource
  - [x] #196 terminate build is not working like expected
  - [x] #197 doxygen history menu shows multiple entries for same file
  - [x] #198 doxyfile selection dialog does not show nested elements
  - [x] #200 invalid custom doxygen identifier found
  - [x] #201 Doxygen Build Console: stderr and stdin are not synchronized

**Comment by anb0s** [comment]
new testing build #209
