### ISSUE TITLE
[v0.12] testing of build 0.12.0.v20170910-1405

### ISSUE THREAD

**Issue by anb0s** [anb0s/eclox#209]
I need help with testing of the build
tag: **V0_12_0_BETA_3**
commit: **e70b1764e6ebc305dec1fe4e6f4f70322690b45c**

It is available at the testing update site now: http://anb0s.github.io/eclox/testing
version: **0.12.0.v20170910-1405**

Doxygen Binaries (Bundle): http://anb0s.github.io/eclox
version: **1.8.13.v20170413-1543**

**Use "Help | Install New Software...", paste the link and select the right version!**

new found issues and enhancement requests:

new fixed issues in this build:
- [x]  #18 Support doxygen upgrade feature
- [x]  #83 context menu entry shown unnecessarily
- [x]  #91 Implement saveas feature
- [x] #108 improve detection of warnings concerning undocumented parameters
- [x] #206 [v0.12] console icons are not shown
- [x] #207 [v0.12] exception if new file created
- [x] #208 [v0.12] java.lang.NullPointerException in Advanced tab

fixed issues with previous build(s):
- [x] #205 [v0.12] testing of build 0.12.0.v20170802-2053
  - [x] #199 add "clear history" to history menu
  - [x] #203 remove from history if "eclox.core.doxygen.RunException: Missing or bad doxyfile"
- [x] #202 [v0.12] testing of build 0.12.0.v20170705-1928
  - [x] #195 java.lang.IllegalArgumentException in createMarkersForResource
  - [x] #196 terminate build is not working like expected
  - [x] #197 doxygen history menu shows multiple entries for same file
  - [x] #198 doxyfile selection dialog does not show nested elements
  - [x] #200 invalid custom doxygen identifier found
  - [x] #201 Doxygen Build Console: stderr and stdin are not synchronized

**Comment by anb0s** [comment]
new build #216
