### ISSUE TITLE
[v0.12] testing of build 0.12.0.v20170925-1924

### ISSUE THREAD

**Issue by anb0s** [anb0s/eclox#216]
I need help with testing of the build
tag: **V0_12_0_BETA_4_HOTFIX**
commit: **40b557ae5c92c34aea24a8085595c70e69fd4b68**

It is available at the testing update site now: http://anb0s.github.io/eclox/testing
version: **0.12.0.v20170925-1924**

Doxygen Binaries (Bundle): http://anb0s.github.io/eclox
version: **1.8.13.v20170413-1543**

**Use "Help | Install New Software...", paste the link and select the right version!**

new found issues and enhancement requests:

new fixed issues in this build:
- [x] #211 add support for the += operator
- [x] #212 add support for multiple lines (lists) concatenated by backslash (\)
- [x] #214 add support for TAG and VALUE format
- [x] #215 add support for line separator

fixed issues with previous build(s):
- [x] #209 [v0.12] testing of build 0.12.0.v20170910-1405
  - [x]  #18 Support doxygen upgrade feature
  - [x]  #83 context menu entry shown unnecessarily
  - [x]  #91 Implement saveas feature
  - [x] #108 improve detection of warnings concerning undocumented parameters
  - [x] #206 [v0.12] console icons are not shown
  - [x] #207 [v0.12] exception if new file created
  - [x] #208 [v0.12] java.lang.NullPointerException in Advanced tab
- [x] #205 [v0.12] testing of build 0.12.0.v20170802-2053
  - [x] #199 add "clear history" to history menu
  - [x] #203 remove from history if "eclox.core.doxygen.RunException: Missing or bad doxyfile"
- [x] #202 [v0.12] testing of build 0.12.0.v20170705-1928
  - [x] #195 java.lang.IllegalArgumentException in createMarkersForResource
  - [x] #196 terminate build is not working like expected
  - [x] #197 doxygen history menu shows multiple entries for same file
  - [x] #198 doxyfile selection dialog does not show nested elements
  - [x] #200 invalid custom doxygen identifier found
  - [x] #201 Doxygen Build Console: stderr and stdin are not synchronized

**Comment by HolgerNie** [comment]
For me the link must be
https://anb0s.github.io/eclox/testing
with http:// I am getting error message
```
Unable to read repository at http://anb0s.github.io/eclox/testing/compositeContent.xml.
org.apache.http.client.ClientProtocolException
```

**Comment by anb0s** [comment]
I'm using http that worked:

![image](https://user-images.githubusercontent.com/95811/30847415-c89aef6c-a29b-11e7-9049-009e03b1825d.png)

BUT i faced this problem with other update sites too. All investigations about such problems that i saw
https://github.com/mikhail-barg/moreclipboard/issues/6
https://github.com/hallvard/plantuml/issues/34
are related to the Eclipse p2 bug:
...
_I've found the p2 bug described here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=470900#c39
the fix is done in Oxygen 4.7: https://bugs.eclipse.org/bugs/show_bug.cgi?id=509891_
...

The solution is to delete cache files (.index) related to the plugin update sites from:
`c:\Users\<USER_NAME>\.eclipse\org.eclipse.oomph.p2\cache\`

e.g. for eclox:
```
http___anb0s.github.io_eclox_doxygen_p2.index
http___anb0s.github.io_eclox_p2.index
...
```
I did not faced such problems with Oxygen, but may be it something else...

**Comment by anb0s** [comment]
0.12.0 released
